name: Deploy to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: SSH into DigitalOcean droplet and pull changes
      run: |
        ssh -vvv -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} unluckytech@161.35.141.18 'cd /home/unluckytech/htdocs/www.unluckytech.com/wp-content && git pull'
